{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_profile-1.0.aar",
          "url": "flutter_local_notifications_profile-1.0.aar",
          "size": 76206,
          "sha512": "f4bd7c0cbe2d954838e02f147e39080fee3d81ce5738ab1831b1f2913b17c69fb49b12a77589c1e27f7cce588128b4db409569994618f19f172a0b8f6519d613",
          "sha256": "324a0561b4fa573db5773a31cc74132b51c99c497bd3dbe8ff8a053210e2279c",
          "sha1": "8a1d7e7a402ec38be6e83268cc0b2fcb8627fc87",
          "md5": "d54f2b4b9203adfec3c423749acb55ea"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_profile-1.0.aar",
          "url": "flutter_local_notifications_profile-1.0.aar",
          "size": 76206,
          "sha512": "f4bd7c0cbe2d954838e02f147e39080fee3d81ce5738ab1831b1f2913b17c69fb49b12a77589c1e27f7cce588128b4db409569994618f19f172a0b8f6519d613",
          "sha256": "324a0561b4fa573db5773a31cc74132b51c99c497bd3dbe8ff8a053210e2279c",
          "sha1": "8a1d7e7a402ec38be6e83268cc0b2fcb8627fc87",
          "md5": "d54f2b4b9203adfec3c423749acb55ea"
        }
      ]
    }
  ]
}
