{
  "formatVersion": "1.1",
  "component": {
    "group": "com.signify.hue.flutterreactiveblelib",
    "module": "reactive_ble_mobile_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        }
      ],
      "files": [
        {
          "name": "reactive_ble_mobile_profile-1.0.aar",
          "url": "reactive_ble_mobile_profile-1.0.aar",
          "size": 281720,
          "sha512": "d62f8c5e5af685f47476474246b468bb03b3581370aa13d765940174f6b80e0ee5ef74991a566bccb68941071e1c2bbcf4139210868c520a20951aec79bbfb0d",
          "sha256": "611fd1bf66a57bc78b6099d974d773878e22b6285a4a76c00f9803e10584f3a9",
          "sha1": "2ac47ee6d4cf807015138d3948703fdb6b717466",
          "md5": "d7ca276392a7a2e08d291bb7a5794f50"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.polidea.rxandroidble2",
          "module": "rxandroidble",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "reactive_ble_mobile_profile-1.0.aar",
          "url": "reactive_ble_mobile_profile-1.0.aar",
          "size": 281720,
          "sha512": "d62f8c5e5af685f47476474246b468bb03b3581370aa13d765940174f6b80e0ee5ef74991a566bccb68941071e1c2bbcf4139210868c520a20951aec79bbfb0d",
          "sha256": "611fd1bf66a57bc78b6099d974d773878e22b6285a4a76c00f9803e10584f3a9",
          "sha1": "2ac47ee6d4cf807015138d3948703fdb6b717466",
          "md5": "d7ca276392a7a2e08d291bb7a5794f50"
        }
      ]
    }
  ]
}
