{
  "formatVersion": "1.1",
  "component": {
    "group": "com.signify.hue.flutterreactiveblelib",
    "module": "reactive_ble_mobile_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        }
      ],
      "files": [
        {
          "name": "reactive_ble_mobile_release-1.0.aar",
          "url": "reactive_ble_mobile_release-1.0.aar",
          "size": 281560,
          "sha512": "4e3e506d0a1bec6073197e2dc4ced93ef22952b1d3b1d537f7a1d3b92d01b99c044217ee2bba9890e54a6420ec75862f0b2b931a7857ae9d6aafacba32c1f43f",
          "sha256": "9e51a24d94d8669416ab61388f560f0ed6671aae396ad02a7581107fd66a4153",
          "sha1": "350655dde1af44611e925e133f0641e9f29c110c",
          "md5": "45aed0394909f1eaa42e2889cfca8e51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.polidea.rxandroidble2",
          "module": "rxandroidble",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "reactive_ble_mobile_release-1.0.aar",
          "url": "reactive_ble_mobile_release-1.0.aar",
          "size": 281560,
          "sha512": "4e3e506d0a1bec6073197e2dc4ced93ef22952b1d3b1d537f7a1d3b92d01b99c044217ee2bba9890e54a6420ec75862f0b2b931a7857ae9d6aafacba32c1f43f",
          "sha256": "9e51a24d94d8669416ab61388f560f0ed6671aae396ad02a7581107fd66a4153",
          "sha1": "350655dde1af44611e925e133f0641e9f29c110c",
          "md5": "45aed0394909f1eaa42e2889cfca8e51"
        }
      ]
    }
  ]
}
