{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.steenbakker.nordicdfu",
    "module": "nordic_dfu_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        }
      ],
      "files": [
        {
          "name": "nordic_dfu_debug-1.0.aar",
          "url": "nordic_dfu_debug-1.0.aar",
          "size": 17833,
          "sha512": "ec099376cce03ee99a5a51e518173682c3f5d6d7dba529f1cbfc69af2315a2eabe28f56621c2bf44a243f8b880e45af0823872ca28c568477a85c17bdfd1c2c2",
          "sha256": "1ca569fd0e1645df1e739f7b05ca16323b381b9a39ebe5c66181121543347d3f",
          "sha1": "9105953057185cb31675f8096fd59f34115784a2",
          "md5": "0ebe9349318dc9e849d1b94af9c4fb41"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "nordic_dfu_debug-1.0.aar",
          "url": "nordic_dfu_debug-1.0.aar",
          "size": 17833,
          "sha512": "ec099376cce03ee99a5a51e518173682c3f5d6d7dba529f1cbfc69af2315a2eabe28f56621c2bf44a243f8b880e45af0823872ca28c568477a85c17bdfd1c2c2",
          "sha256": "1ca569fd0e1645df1e739f7b05ca16323b381b9a39ebe5c66181121543347d3f",
          "sha1": "9105953057185cb31675f8096fd59f34115784a2",
          "md5": "0ebe9349318dc9e849d1b94af9c4fb41"
        }
      ]
    }
  ]
}
